//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenceDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExpanceDBEntities : DbContext
    {
        public ExpanceDBEntities()
            : base("name=ExpanceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompanyMaster> CompanyMasters { get; set; }
        public virtual DbSet<IncomeMaster> IncomeMasters { get; set; }
        public virtual DbSet<tbl_Income> tbl_Income { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    }
}
